version: '3.9'

services:
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "5050:8080"
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl --silent http://localhost:8080 || exit 1"]
      interval: 10s
      retries: 5
      start_period: 20s

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Daniel123!"
      ACCEPT_EULA: "Y"
    platform: linux/amd64
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Daniel123!", "-Q", "SELECT 1"]
      interval: 10s
      retries: 10
      start_period: 20s

volumes:
  sql_data:
